services:
  patron_c2_server:
    image: patron_c2_server
    build: server
    restart: always
    command: sh -c "go run server/server.go"
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      internal_c2_network:
        ipv4_address: "${DOCKER_INTERNAL}.5"
    ports:
      - "${C2SERVER_PORT}:${C2SERVER_PORT}"
    depends_on:
      patron_c2_postgres:
        condition: service_healthy

  patron_c2_api:
    image: patron_c2_server
    build: api
    restart: always
    command: sh -c "go run api/api.go"
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      internal_c2_network:
        ipv4_address: "${DOCKER_INTERNAL}.6"
    ports:
      - 8000:8000
    depends_on:
      patron_c2_postgres:
        condition: service_healthy

  patron_c2_frontend:
    image: node:22-alpine
    command: sh -c "npm install && npm start"
    working_dir: /app
    restart: always
    volumes:
      - ./ui:/app
    networks:
      internal_c2_network:
        ipv4_address: "${DOCKER_INTERNAL}.7"
    ports:
            - 8081:8081
    depends_on:
      - patron_c2_api

  patron_c2_postgres:
    image: postgres:latest
    restart: always
    container_name: patron_c2_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      internal_c2_network:
        ipv4_address: "${DOCKER_INTERNAL}.9"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  internal_c2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_INTERNAL}.0/16"
