FROM node:22-alpine AS build

ARG PORT

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV NO_PROXY=${NO_PROXY}

WORKDIR /app

RUN apk add curl

COPY ./ui /app/
RUN npm install

EXPOSE ${PORT}

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=5 \
  CMD curl -fL localhost:${PORT}/robots.txt || exit 1

CMD ["sh", "-c", "npm start"]
