services:
  patron_c2_server:
    image: patron_c2_server
    build: server
    restart: always
    command: sh -c "go run server/server.go"
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      internal_c2_network:
        ipv4_address: 172.18.0.5
    ports:
      - 9000:9000

  patron_c2_api:
    image: patron_c2_server
    build: Web/server
    restart: always
    command: sh -c "go run Web/server/webserver.go"
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      internal_c2_network:
        ipv4_address: 172.18.0.6
    # ports:
    #   - 8000:8000

  patron_c2_frontend:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    working_dir: /app
    restart: always
    volumes:
      - ./Web/client:/app
    networks:
      internal_c2_network:
        ipv4_address: 172.18.0.7
    # ports:
    #   - 8081:8081
  
  patron_c2_nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./nginx:/etc/nginx/templates
    networks:
      internal_c2_network:
        ipv4_address: 172.18.0.8
    ports:
    - "8082:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80

  patron_c2_postgres:
    image: postgres:latest
    restart: always
    container_name: patron_c2_postgres
    environment:
      POSTGRES_USER: patron
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: patron
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      internal_c2_network:
        ipv4_address: 172.18.0.9

networks:
  internal_c2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16