FROM postgres:latest

ARG DB_PORT

ENV HTTP_PROXY=''
ENV HTTPS_PROXY=''
ENV NO_PROXY=''

ENV POSTGRES_USER=postgres

EXPOSE ${DB_PORT}

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD pg_isready -U $POSTGRES_USER
