services:
  patron_c2_server:
    image: patron-server
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      DB_HOST: patron_c2_postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      C2SERVER_IP: patron_c2_server
      C2SERVER_PORT: ${C2SERVER_PORT}
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    networks:
      - internal_c2_network
    ports:
      - "${C2SERVER_PORT}:${C2SERVER_PORT}"
    depends_on:
      patron_c2_postgres:
        condition: service_healthy

  patron_c2_api:
    image: patron-api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DB_HOST: patron_c2_postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      PUBLIC_KEY: ${PUBLIC_KEY}
      REPO_DIR: ${REPO_DIR}
      JWT_KEY: ${JWT_KEY}
      ADMIN_AUTH_USER: ${ADMIN_AUTH_USER}
      ADMIN_AUTH_PASS: ${ADMIN_AUTH_PASS}
      REDIRECTOR_PORT: ${REDIRECTOR_PORT}
      REACT_APP_NGINX_IP: ${REACT_APP_NGINX_IP}
      REACT_APP_NGINX_PORT: ${REACT_APP_NGINX_PORT}
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./payloads:/app/payloads
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal_c2_network
    depends_on:
      patron_c2_postgres:
        condition: service_healthy

  patron_c2_frontend:
    image: patron-ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    working_dir: /app
    restart: always
    volumes:
      - .env:/app/.env
      - ./logs:/app/logs
    environment:
      - PORT=${PORT}
    networks:
      - internal_c2_network
    depends_on:
      patron_c2_api:
        condition: service_healthy

  patron_c2_postgres:
    image: patron-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - internal_c2_network

  patron_c2_nginx:
    image: patron-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs/server.pem:/etc/nginx/ssl/nginx.crt
      - ./certs/server.key:/etc/nginx/ssl/nginx.key
    environment:
      - REACT_SERVER=patron_c2_frontend:${PORT}
      - REACT_APP_NGINX_PORT=${REACT_APP_NGINX_PORT}
      - API_SERVER=patron_c2_api:${WEBSERVER_PORT}
    networks:
      - internal_c2_network
    ports:
      - "${REACT_APP_NGINX_PORT}:${REACT_APP_NGINX_PORT}"
    depends_on:
      patron_c2_frontend:
        condition: service_healthy

networks:
  internal_c2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_INTERNAL}.0/16"