{
 "title": "Patron Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Patron Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Agents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "patron_api_agents_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Agents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "patron_api_agents_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Offline Agents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "patron_api_agents_offline", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Redirectors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patron_redirectors_redirectors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Redirectors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patron_redirectors_redirectors_online",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Redirectors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patron_redirectors_redirectors_offline",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Timings And Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "API Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, method, url) (\r\n    rate(patron_api_request_duration_seconds_bucket[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "200 Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "sum by (method, url) (\r\n  rate(patron_api_requests_total{code=\"200\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication/Authorization Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (code, url) (\r\n  rate(patron_api_requests_total{code=~\"401|403\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 4xx's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "sum by (code, uri) (\r\n  rate(patron_api_requests_total{code=~\"4..\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 5xx's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (code, uri) (\r\n  rate(patron_api_requests_total{code=~\"5..\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC pauses (p100)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(go_gc_duration_seconds{quantile=\"1.0\", job=\"patron-api\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC pauses (p75)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(go_gc_duration_seconds{quantile=\"0.75\", job=\"patron-api\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total time spent in GC pauses per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=\"patron-api\"}[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC cycles per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count{job=\"patron-api\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Tuning Knobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "GOGC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "go_gc_gogc_percent{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GOMEMLIMIT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_gc_gomemlimit_bytes{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects Allocated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 589 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"patron-api\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Objects Freed Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 589 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total{job=\"patron-api\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes Allocated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 597 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"patron-api\"}[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap Size / Memory Footprint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 556 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Heap Reserved",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 556 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Next GC Target",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 580 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 557 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Change in goroutines",
     "type": "timeseries",
     "description": "This should always flap, or stay around 0. Otherwise, there are probably leaking goroutines",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 557 },
     "targets": [
      {
       "expr": "(go_goroutines{job=\"patron-api\"} - go_goroutines{job=\"patron-api\"} offset 10m)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 558 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "go_threads{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GOMAXPROCS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 558 },
     "targets": [
      {
       "expr": "go_sched_gomaxprocs_threads{job=\"patron-api\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}