FROM golang:1.23.3 AS bot-builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./bot .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /app/bot

FROM alpine:latest
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

WORKDIR /root/

COPY --from=bot-builder /app/bot ./bot

RUN apk --no-cache add ca-certificates

ENV REACT_APP_NGINX_IP=patron_c2_nginx
ENV REACT_APP_NGINX_PORT=8443

CMD ["./discord-bot"]
